packages:
  - packages/*
  - plugins/*
catalog:
  '@types/node': ^22.0.0
  typescript: 5.7.3
  tsx: 4.19.3
  tsc-alias: 1.8.10
  '@eslint/js': 9.26.0
  eslint: 9.26.0
  prettier: 3.5.3
  react: 18.3.1
  react-dom: 18.3.1
  '@types/react': 18.3.8
  '@types/react-dom': 18.3.0
  autoprefixer: 10.4.20
  tailwindcss: 3.4.11
  postcss: 8.4.38
  postcss-prefixer: 3.0.0
  vite: 6.3.5
  vitest: 3.0.7
  '@vitejs/plugin-react': 4.3.4
  vite-plugin-svgr: 4.3.0
  vite-tsconfig-paths: 5.1.4
  zod: 3.24.1
ignoredBuiltDependencies:
  - unrs-resolver
