packages:
  - packages/*
  - plugins/*

catalog:
  '@eslint/js': 9.32.0
  '@tailwindcss/vite': 4.1.13
  '@types/node': ^22.17.2
  '@types/react': 19.1.3
  '@types/react-dom': 19.1.3
  '@vitejs/plugin-react': 5.0.2
  autoprefixer: 10.4.20
  cpx2: 8.0.0
  eslint: 9.32.0
  prettier: 3.6.2
  react: 19.1.0
  react-dom: 19.1.0
  tailwindcss: 4.1.13
  tsx: 4.19.3
  typescript: 5.8.3
  vite: 7.1.5
  vite-plugin-svgr: 4.5.0
  vitest: 3.2.4
  zod: 3.25.76

ignoredBuiltDependencies:
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - cpu-features
  - esbuild
  - protobufjs
  - ssh2
  - unrs-resolver
