packages:
  - packages/*
  - plugins/*
catalog:
  cpx2: 8.0.0
  '@types/node': ^22.0.0
  typescript: 5.7.3
  tsx: 4.19.3
  '@eslint/js': 9.26.0
  eslint: 9.26.0
  prettier: 3.5.3
  react: 19.1.0
  react-dom: 19.1.0
  '@types/react': 19.1.3
  '@types/react-dom': 19.1.3
  autoprefixer: 10.4.20
  '@tailwindcss/vite': 4.1.6
  tailwindcss: 4.1.6
  vite: 6.3.5
  vitest: 3.0.7
  '@vitejs/plugin-react': 4.4.1
  vite-plugin-svgr: 4.3.0
  zod: 3.24.1
ignoredBuiltDependencies:
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - cpu-features
  - esbuild
  - protobufjs
  - ssh2
  - unrs-resolver
