packages:
  - 'packages/*'
  - 'plugins/*'

catalog:
  # Node
  '@types/node': '^20.0.0'

  # Typescript
  typescript: 5.5.4
  tsx: 4.19.1
  tsc-alias: 1.8.10

  # Linting / Formatting
  '@eslint/js': 9.17.0
  eslint: 9.17.0
  '@types/eslint': 9.6.1
  '@types/eslint__js': 8.42.3
  prettier: 3.4.2

  # React
  react: 18.3.1
  react-dom: 18.3.1
  '@types/react': 18.3.8
  '@types/react-dom': 18.3.0

  # Vite
  vite: 5.4.7
  vitest: 2.1.1
  '@vitejs/plugin-react': 4.3.1
  vite-tsconfig-paths: 5.0.0

  # Validation
  zod: 3.24.1
