packages:
  - apps/*

ignoredBuiltDependencies:
  - '@tailwindcss/oxide'
  - msgpackr-extract
  - unrs-resolver

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry-internal/node-cpu-profiler'
  - '@sentry/profiling-node'
  - esbuild
  - prisma
