mutation RegisterWithEmailPassword($input: RegisterWithEmailPasswordInput!) {
  registerWithEmailPassword(input: $input) {
    session {
      userId
      roles
    }
  }
}

mutation LoginWithEmailPassword($input: LoginWithEmailPasswordInput!) {
  loginWithEmailPassword(input: $input) {
    session {
      userId
      roles
    }
  }
}
