import { oxfmtConfigReact } from '@baseplate-dev/tools/oxfmt-config-react';

export default {
  ...oxfmtConfigReact,
  // generated by TanStack Router
  ignorePatterns: [...oxfmtConfigReact.ignorePatterns, '**/route-tree.gen.ts'],
};
