#!/usr/bin/env bash

BASENAME=$(basename "$PWD")
SAFE_COMPOSE_PROJECT_NAME=$(printf '%s' "$BASENAME" \
  | tr '[:upper:]' '[:lower:]' \
  | sed -E 's/[^a-z0-9_-]+/-/g; s/^-+//; s/-+$//')
[ -n "$SAFE_COMPOSE_PROJECT_NAME" ] || SAFE_COMPOSE_PROJECT_NAME="devcontainer"

# Generate .devcontainer/.env for docker-compose variable substitution
ENV_FILE="${PWD}/.devcontainer/.env"
cat > "$ENV_FILE" <<EOF
# Auto-generated by setup-mounts.sh — do not edit manually
COMPOSE_PROJECT_NAME=${SAFE_COMPOSE_PROJECT_NAME}
WORKSPACE_BASENAME=${BASENAME}
LOCAL_WORKSPACE_FOLDER=${PWD}
TZ=${TZ:-America/Los_Angeles}
EOF
echo "Generated docker-compose env file: $ENV_FILE"

# Create mounts directory if it doesn't exist
MOUNTS_DIR="${PWD}/.devcontainer/mounts"
if [ ! -d "$MOUNTS_DIR" ]; then
    echo "Creating mounts directory: $MOUNTS_DIR"
    mkdir -p "$MOUNTS_DIR"
else
    echo "Mounts directory already exists: $MOUNTS_DIR"
fi

# Ensure secrets file exists (prevents bind mount failure if missing)
# User should create ~/.devcontainers/<basename>.env with GH_TOKEN=ghp_xxx
SECRETS_DIR="$HOME/.devcontainers"
SECRETS_FILE="$SECRETS_DIR/${BASENAME}.env"

mkdir -p "$SECRETS_DIR"
if [ ! -f "$SECRETS_FILE" ]; then
    touch "$SECRETS_FILE"
    echo "Created empty secrets file: $SECRETS_FILE"
    echo "Add GH_TOKEN=ghp_xxx to enable GitHub auth"
fi
chmod 600 "$SECRETS_FILE"

# Ensure Claude skills directory exists (prevents bind mount failure if missing)
CLAUDE_SKILLS_DIR="$HOME/.claude/skills"
if [ ! -d "$CLAUDE_SKILLS_DIR" ]; then
    mkdir -p "$CLAUDE_SKILLS_DIR"
    echo "Created Claude skills directory: $CLAUDE_SKILLS_DIR"
fi

echo "Mount setup completed successfully"
