/* eslint-disable */
/* prettier-ignore */

export type introspection_types = {
    'Boolean': unknown;
    'CreatePresignedDownloadUrlInput': { kind: 'INPUT_OBJECT'; name: 'CreatePresignedDownloadUrlInput'; isOneOf: false; inputFields: [{ name: 'fileId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; }; defaultValue: null }]; };
    'CreatePresignedDownloadUrlPayload': { kind: 'OBJECT'; name: 'CreatePresignedDownloadUrlPayload'; fields: { 'url': { name: 'url'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'CreatePresignedUploadUrlInput': { kind: 'INPUT_OBJECT'; name: 'CreatePresignedUploadUrlInput'; isOneOf: false; inputFields: [{ name: 'category'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'ENUM'; name: 'FileCategory'; ofType: null; }; }; defaultValue: null }, { name: 'contentType'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'filename'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'size'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; defaultValue: null }]; };
    'CreatePresignedUploadUrlPayload': { kind: 'OBJECT'; name: 'CreatePresignedUploadUrlPayload'; fields: { 'fields': { name: 'fields'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'PresignedUrlField'; ofType: null; }; }; } }; 'file': { name: 'file'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'File'; ofType: null; }; } }; 'method': { name: 'method'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'url': { name: 'url'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'CreateTodoItemData': { kind: 'INPUT_OBJECT'; name: 'CreateTodoItemData'; isOneOf: false; inputFields: [{ name: 'assigneeId'; type: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; defaultValue: null }, { name: 'attachments'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'TodoItemAttachmentsNestedInput'; ofType: null; }; }; }; defaultValue: null }, { name: 'done'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; }; defaultValue: null }, { name: 'position'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; defaultValue: null }, { name: 'text'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'todoListId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; }; defaultValue: null }]; };
    'CreateTodoItemInput': { kind: 'INPUT_OBJECT'; name: 'CreateTodoItemInput'; isOneOf: false; inputFields: [{ name: 'data'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'CreateTodoItemData'; ofType: null; }; }; defaultValue: null }]; };
    'CreateTodoItemPayload': { kind: 'OBJECT'; name: 'CreateTodoItemPayload'; fields: { 'todoItem': { name: 'todoItem'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TodoItem'; ofType: null; }; } }; }; };
    'CreateTodoListData': { kind: 'INPUT_OBJECT'; name: 'CreateTodoListData'; isOneOf: false; inputFields: [{ name: 'coverPhoto'; type: { kind: 'INPUT_OBJECT'; name: 'FileInput'; ofType: null; }; defaultValue: null }, { name: 'createdAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; defaultValue: null }, { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'ownerId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; }; defaultValue: null }, { name: 'position'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; defaultValue: null }, { name: 'status'; type: { kind: 'ENUM'; name: 'TodoListStatus'; ofType: null; }; defaultValue: null }]; };
    'CreateTodoListInput': { kind: 'INPUT_OBJECT'; name: 'CreateTodoListInput'; isOneOf: false; inputFields: [{ name: 'data'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'CreateTodoListData'; ofType: null; }; }; defaultValue: null }]; };
    'CreateTodoListPayload': { kind: 'OBJECT'; name: 'CreateTodoListPayload'; fields: { 'todoList': { name: 'todoList'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TodoList'; ofType: null; }; } }; }; };
    'CreateTodoListShareData': { kind: 'INPUT_OBJECT'; name: 'CreateTodoListShareData'; isOneOf: false; inputFields: [{ name: 'createdAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; defaultValue: null }, { name: 'todoListId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; }; defaultValue: null }, { name: 'updatedAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; defaultValue: null }, { name: 'userId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; }; defaultValue: null }]; };
    'CreateTodoListShareInput': { kind: 'INPUT_OBJECT'; name: 'CreateTodoListShareInput'; isOneOf: false; inputFields: [{ name: 'data'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'CreateTodoListShareData'; ofType: null; }; }; defaultValue: null }]; };
    'CreateTodoListSharePayload': { kind: 'OBJECT'; name: 'CreateTodoListSharePayload'; fields: { 'todoListShare': { name: 'todoListShare'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TodoListShare'; ofType: null; }; } }; }; };
    'CreateUserData': { kind: 'INPUT_OBJECT'; name: 'CreateUserData'; isOneOf: false; inputFields: [{ name: 'customer'; type: { kind: 'INPUT_OBJECT'; name: 'UserCustomerNestedInput'; ofType: null; }; defaultValue: null }, { name: 'email'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'images'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'UserImagesNestedInput'; ofType: null; }; }; }; defaultValue: null }, { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'roles'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'UserRolesNestedInput'; ofType: null; }; }; }; defaultValue: null }, { name: 'userProfile'; type: { kind: 'INPUT_OBJECT'; name: 'UserUserProfileNestedInput'; ofType: null; }; defaultValue: null }]; };
    'CreateUserInput': { kind: 'INPUT_OBJECT'; name: 'CreateUserInput'; isOneOf: false; inputFields: [{ name: 'data'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'CreateUserData'; ofType: null; }; }; defaultValue: null }]; };
    'CreateUserPayload': { kind: 'OBJECT'; name: 'CreateUserPayload'; fields: { 'user': { name: 'user'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'User'; ofType: null; }; } }; }; };
    'Customer': { kind: 'OBJECT'; name: 'Customer'; fields: { 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'stripeCustomerId': { name: 'stripeCustomerId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'user': { name: 'user'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'User'; ofType: null; }; } }; }; };
    'Date': unknown;
    'DateTime': unknown;
    'DeleteTodoItemInput': { kind: 'INPUT_OBJECT'; name: 'DeleteTodoItemInput'; isOneOf: false; inputFields: [{ name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; }; defaultValue: null }]; };
    'DeleteTodoItemPayload': { kind: 'OBJECT'; name: 'DeleteTodoItemPayload'; fields: { 'todoItem': { name: 'todoItem'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TodoItem'; ofType: null; }; } }; }; };
    'DeleteTodoListInput': { kind: 'INPUT_OBJECT'; name: 'DeleteTodoListInput'; isOneOf: false; inputFields: [{ name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; }; defaultValue: null }]; };
    'DeleteTodoListPayload': { kind: 'OBJECT'; name: 'DeleteTodoListPayload'; fields: { 'todoList': { name: 'todoList'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TodoList'; ofType: null; }; } }; }; };
    'DeleteTodoListShareInput': { kind: 'INPUT_OBJECT'; name: 'DeleteTodoListShareInput'; isOneOf: false; inputFields: [{ name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'TodoListSharePrimaryKey'; ofType: null; }; }; defaultValue: null }]; };
    'DeleteTodoListSharePayload': { kind: 'OBJECT'; name: 'DeleteTodoListSharePayload'; fields: { 'todoListShare': { name: 'todoListShare'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TodoListShare'; ofType: null; }; } }; }; };
    'DeleteUserInput': { kind: 'INPUT_OBJECT'; name: 'DeleteUserInput'; isOneOf: false; inputFields: [{ name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; }; defaultValue: null }]; };
    'DeleteUserPayload': { kind: 'OBJECT'; name: 'DeleteUserPayload'; fields: { 'user': { name: 'user'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'User'; ofType: null; }; } }; }; };
    'File': { kind: 'OBJECT'; name: 'File'; fields: { 'category': { name: 'category'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'filename': { name: 'filename'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'mimeType': { name: 'mimeType'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'publicUrl': { name: 'publicUrl'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'uploader': { name: 'uploader'; type: { kind: 'OBJECT'; name: 'User'; ofType: null; } }; }; };
    'FileCategory': { name: 'FileCategory'; enumValues: 'TODO_LIST_COVER_PHOTO' | 'USER_IMAGE_FILE' | 'USER_PROFILE_AVATAR'; };
    'FileInput': { kind: 'INPUT_OBJECT'; name: 'FileInput'; isOneOf: false; inputFields: [{ name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; }; defaultValue: null }, { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }]; };
    'ID': unknown;
    'Int': unknown;
    'JSON': unknown;
    'JSONObject': unknown;
    'Mutation': { kind: 'OBJECT'; name: 'Mutation'; fields: { 'createPresignedDownloadUrl': { name: 'createPresignedDownloadUrl'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CreatePresignedDownloadUrlPayload'; ofType: null; }; } }; 'createPresignedUploadUrl': { name: 'createPresignedUploadUrl'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CreatePresignedUploadUrlPayload'; ofType: null; }; } }; 'createTodoItem': { name: 'createTodoItem'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CreateTodoItemPayload'; ofType: null; }; } }; 'createTodoList': { name: 'createTodoList'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CreateTodoListPayload'; ofType: null; }; } }; 'createTodoListShare': { name: 'createTodoListShare'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CreateTodoListSharePayload'; ofType: null; }; } }; 'createUser': { name: 'createUser'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'CreateUserPayload'; ofType: null; }; } }; 'deleteTodoItem': { name: 'deleteTodoItem'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DeleteTodoItemPayload'; ofType: null; }; } }; 'deleteTodoList': { name: 'deleteTodoList'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DeleteTodoListPayload'; ofType: null; }; } }; 'deleteTodoListShare': { name: 'deleteTodoListShare'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DeleteTodoListSharePayload'; ofType: null; }; } }; 'deleteUser': { name: 'deleteUser'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'DeleteUserPayload'; ofType: null; }; } }; 'updateTodoItem': { name: 'updateTodoItem'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'UpdateTodoItemPayload'; ofType: null; }; } }; 'updateTodoList': { name: 'updateTodoList'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'UpdateTodoListPayload'; ofType: null; }; } }; 'updateTodoListShare': { name: 'updateTodoListShare'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'UpdateTodoListSharePayload'; ofType: null; }; } }; 'updateUser': { name: 'updateUser'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'UpdateUserPayload'; ofType: null; }; } }; }; };
    'PresignedUrlField': { kind: 'OBJECT'; name: 'PresignedUrlField'; fields: { 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'value': { name: 'value'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'Query': { kind: 'OBJECT'; name: 'Query'; fields: { 'file': { name: 'file'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'File'; ofType: null; }; } }; 'files': { name: 'files'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'File'; ofType: null; }; }; }; } }; 'todoItem': { name: 'todoItem'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TodoItem'; ofType: null; }; } }; 'todoItems': { name: 'todoItems'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TodoItem'; ofType: null; }; }; }; } }; 'todoList': { name: 'todoList'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TodoList'; ofType: null; }; } }; 'todoListShare': { name: 'todoListShare'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TodoListShare'; ofType: null; }; } }; 'todoListShares': { name: 'todoListShares'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TodoListShare'; ofType: null; }; }; }; } }; 'todoLists': { name: 'todoLists'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TodoList'; ofType: null; }; }; }; } }; 'user': { name: 'user'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'User'; ofType: null; }; } }; 'users': { name: 'users'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'User'; ofType: null; }; }; }; } }; 'viewer': { name: 'viewer'; type: { kind: 'OBJECT'; name: 'User'; ofType: null; } }; }; };
    'String': unknown;
    'TodoItem': { kind: 'OBJECT'; name: 'TodoItem'; fields: { 'attachments': { name: 'attachments'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TodoItemAttachment'; ofType: null; }; }; }; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'done': { name: 'done'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'position': { name: 'position'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'text': { name: 'text'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'todoList': { name: 'todoList'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TodoList'; ofType: null; }; } }; 'todoListId': { name: 'todoListId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; }; };
    'TodoItemAttachment': { kind: 'OBJECT'; name: 'TodoItemAttachment'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'position': { name: 'position'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'tags': { name: 'tags'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TodoItemAttachmentTag'; ofType: null; }; }; }; } }; 'todoItem': { name: 'todoItem'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TodoItem'; ofType: null; }; } }; 'todoItemId': { name: 'todoItemId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'url': { name: 'url'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; }; };
    'TodoItemAttachmentTag': { kind: 'OBJECT'; name: 'TodoItemAttachmentTag'; fields: { 'tag': { name: 'tag'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'todoItemAttachment': { name: 'todoItemAttachment'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TodoItemAttachment'; ofType: null; }; } }; 'todoItemAttachmentId': { name: 'todoItemAttachmentId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; } }; }; };
    'TodoItemAttachmentTagsNestedInput': { kind: 'INPUT_OBJECT'; name: 'TodoItemAttachmentTagsNestedInput'; isOneOf: false; inputFields: [{ name: 'tag'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }]; };
    'TodoItemAttachmentsNestedInput': { kind: 'INPUT_OBJECT'; name: 'TodoItemAttachmentsNestedInput'; isOneOf: false; inputFields: [{ name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; defaultValue: null }, { name: 'position'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; }; defaultValue: null }, { name: 'tags'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'TodoItemAttachmentTagsNestedInput'; ofType: null; }; }; }; defaultValue: null }, { name: 'url'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }]; };
    'TodoList': { kind: 'OBJECT'; name: 'TodoList'; fields: { 'coverPhoto': { name: 'coverPhoto'; type: { kind: 'OBJECT'; name: 'File'; ofType: null; } }; 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'owner': { name: 'owner'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'User'; ofType: null; }; } }; 'ownerId': { name: 'ownerId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; } }; 'position': { name: 'position'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; } }; 'status': { name: 'status'; type: { kind: 'ENUM'; name: 'TodoListStatus'; ofType: null; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; }; };
    'TodoListShare': { kind: 'OBJECT'; name: 'TodoListShare'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'todoList': { name: 'todoList'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TodoList'; ofType: null; }; } }; 'todoListId': { name: 'todoListId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'user': { name: 'user'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'User'; ofType: null; }; } }; 'userId': { name: 'userId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; } }; }; };
    'TodoListSharePrimaryKey': { kind: 'INPUT_OBJECT'; name: 'TodoListSharePrimaryKey'; isOneOf: false; inputFields: [{ name: 'todoListId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; }; defaultValue: null }, { name: 'userId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; }; defaultValue: null }]; };
    'TodoListStatus': { name: 'TodoListStatus'; enumValues: 'ACTIVE' | 'INACTIVE'; };
    'UpdateTodoItemData': { kind: 'INPUT_OBJECT'; name: 'UpdateTodoItemData'; isOneOf: false; inputFields: [{ name: 'assigneeId'; type: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; defaultValue: null }, { name: 'attachments'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'TodoItemAttachmentsNestedInput'; ofType: null; }; }; }; defaultValue: null }, { name: 'done'; type: { kind: 'SCALAR'; name: 'Boolean'; ofType: null; }; defaultValue: null }, { name: 'position'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: 'text'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'todoListId'; type: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; defaultValue: null }]; };
    'UpdateTodoItemInput': { kind: 'INPUT_OBJECT'; name: 'UpdateTodoItemInput'; isOneOf: false; inputFields: [{ name: 'data'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'UpdateTodoItemData'; ofType: null; }; }; defaultValue: null }, { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; }; defaultValue: null }]; };
    'UpdateTodoItemPayload': { kind: 'OBJECT'; name: 'UpdateTodoItemPayload'; fields: { 'todoItem': { name: 'todoItem'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TodoItem'; ofType: null; }; } }; }; };
    'UpdateTodoListData': { kind: 'INPUT_OBJECT'; name: 'UpdateTodoListData'; isOneOf: false; inputFields: [{ name: 'coverPhoto'; type: { kind: 'INPUT_OBJECT'; name: 'FileInput'; ofType: null; }; defaultValue: null }, { name: 'createdAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; defaultValue: null }, { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'ownerId'; type: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; defaultValue: null }, { name: 'position'; type: { kind: 'SCALAR'; name: 'Int'; ofType: null; }; defaultValue: null }, { name: 'status'; type: { kind: 'ENUM'; name: 'TodoListStatus'; ofType: null; }; defaultValue: null }]; };
    'UpdateTodoListInput': { kind: 'INPUT_OBJECT'; name: 'UpdateTodoListInput'; isOneOf: false; inputFields: [{ name: 'data'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'UpdateTodoListData'; ofType: null; }; }; defaultValue: null }, { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; }; defaultValue: null }]; };
    'UpdateTodoListPayload': { kind: 'OBJECT'; name: 'UpdateTodoListPayload'; fields: { 'todoList': { name: 'todoList'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TodoList'; ofType: null; }; } }; }; };
    'UpdateTodoListShareData': { kind: 'INPUT_OBJECT'; name: 'UpdateTodoListShareData'; isOneOf: false; inputFields: [{ name: 'createdAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; defaultValue: null }, { name: 'todoListId'; type: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; defaultValue: null }, { name: 'updatedAt'; type: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; defaultValue: null }, { name: 'userId'; type: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; defaultValue: null }]; };
    'UpdateTodoListShareInput': { kind: 'INPUT_OBJECT'; name: 'UpdateTodoListShareInput'; isOneOf: false; inputFields: [{ name: 'data'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'UpdateTodoListShareData'; ofType: null; }; }; defaultValue: null }, { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'TodoListSharePrimaryKey'; ofType: null; }; }; defaultValue: null }]; };
    'UpdateTodoListSharePayload': { kind: 'OBJECT'; name: 'UpdateTodoListSharePayload'; fields: { 'todoListShare': { name: 'todoListShare'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TodoListShare'; ofType: null; }; } }; }; };
    'UpdateUserData': { kind: 'INPUT_OBJECT'; name: 'UpdateUserData'; isOneOf: false; inputFields: [{ name: 'customer'; type: { kind: 'INPUT_OBJECT'; name: 'UserCustomerNestedInput'; ofType: null; }; defaultValue: null }, { name: 'email'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'images'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'UserImagesNestedInput'; ofType: null; }; }; }; defaultValue: null }, { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'roles'; type: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'UserRolesNestedInput'; ofType: null; }; }; }; defaultValue: null }, { name: 'userProfile'; type: { kind: 'INPUT_OBJECT'; name: 'UserUserProfileNestedInput'; ofType: null; }; defaultValue: null }]; };
    'UpdateUserInput': { kind: 'INPUT_OBJECT'; name: 'UpdateUserInput'; isOneOf: false; inputFields: [{ name: 'data'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'UpdateUserData'; ofType: null; }; }; defaultValue: null }, { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; }; defaultValue: null }]; };
    'UpdateUserPayload': { kind: 'OBJECT'; name: 'UpdateUserPayload'; fields: { 'user': { name: 'user'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'User'; ofType: null; }; } }; }; };
    'User': { kind: 'OBJECT'; name: 'User'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'customer': { name: 'customer'; type: { kind: 'OBJECT'; name: 'Customer'; ofType: null; } }; 'email': { name: 'email'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'name': { name: 'name'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'roles': { name: 'roles'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'UserRole'; ofType: null; }; }; }; } }; 'todoLists': { name: 'todoLists'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'LIST'; name: never; ofType: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'TodoList'; ofType: null; }; }; }; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'userProfile': { name: 'userProfile'; type: { kind: 'OBJECT'; name: 'UserProfile'; ofType: null; } }; }; };
    'UserCustomerNestedInput': { kind: 'INPUT_OBJECT'; name: 'UserCustomerNestedInput'; isOneOf: false; inputFields: [{ name: 'stripeCustomerId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }]; };
    'UserImage': { kind: 'OBJECT'; name: 'UserImage'; fields: { 'file': { name: 'file'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'File'; ofType: null; }; } }; 'fileId': { name: 'fileId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'userId': { name: 'userId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; } }; }; };
    'UserImagesNestedInput': { kind: 'INPUT_OBJECT'; name: 'UserImagesNestedInput'; isOneOf: false; inputFields: [{ name: 'caption'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }, { name: 'file'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'INPUT_OBJECT'; name: 'FileInput'; ofType: null; }; }; defaultValue: null }, { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; defaultValue: null }]; };
    'UserProfile': { kind: 'OBJECT'; name: 'UserProfile'; fields: { 'avatar': { name: 'avatar'; type: { kind: 'OBJECT'; name: 'File'; ofType: null; } }; 'avatarId': { name: 'avatarId'; type: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; } }; 'bio': { name: 'bio'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'birthDay': { name: 'birthDay'; type: { kind: 'SCALAR'; name: 'Date'; ofType: null; } }; 'id': { name: 'id'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; } }; 'twitterHandle': { name: 'twitterHandle'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; } }; 'user': { name: 'user'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'User'; ofType: null; }; } }; 'userId': { name: 'userId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; } }; }; };
    'UserRole': { kind: 'OBJECT'; name: 'UserRole'; fields: { 'createdAt': { name: 'createdAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'role': { name: 'role'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; } }; 'updatedAt': { name: 'updatedAt'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'DateTime'; ofType: null; }; } }; 'user': { name: 'user'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'OBJECT'; name: 'User'; ofType: null; }; } }; 'userId': { name: 'userId'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'Uuid'; ofType: null; }; } }; }; };
    'UserRolesNestedInput': { kind: 'INPUT_OBJECT'; name: 'UserRolesNestedInput'; isOneOf: false; inputFields: [{ name: 'role'; type: { kind: 'NON_NULL'; name: never; ofType: { kind: 'SCALAR'; name: 'String'; ofType: null; }; }; defaultValue: null }]; };
    'UserUserProfileNestedInput': { kind: 'INPUT_OBJECT'; name: 'UserUserProfileNestedInput'; isOneOf: false; inputFields: [{ name: 'avatar'; type: { kind: 'INPUT_OBJECT'; name: 'FileInput'; ofType: null; }; defaultValue: null }, { name: 'bio'; type: { kind: 'SCALAR'; name: 'String'; ofType: null; }; defaultValue: null }, { name: 'birthDay'; type: { kind: 'SCALAR'; name: 'Date'; ofType: null; }; defaultValue: null }, { name: 'id'; type: { kind: 'SCALAR'; name: 'ID'; ofType: null; }; defaultValue: null }]; };
    'Uuid': unknown;
};

/** An IntrospectionQuery representation of your schema.
 *
 * @remarks
 * This is an introspection of your schema saved as a file by GraphQLSP.
 * It will automatically be used by `gql.tada` to infer the types of your GraphQL documents.
 * If you need to reuse this data or update your `scalars`, update `tadaOutputLocation` to
 * instead save to a .ts instead of a .d.ts file.
 */
export type introspection = {
  name: never;
  query: 'Query';
  mutation: 'Mutation';
  subscription: never;
  types: introspection_types;
};

import * as gqlTada from 'gql.tada';

declare module 'gql.tada' {
  interface setupSchema {
    introspection: introspection
  }
}