fragment FileInput on TPL_FILE_TYPE {
  id
  filename
  publicUrl
}

mutation CreateUploadUrl($input: CreatePresignedUploadUrlInput!) {
  createPresignedUploadUrl(input: $input) {
    url
    fields {
      name
      value
    }
    method
    file {
      ...FileInput
    }
  }
}
