/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as PluginsRouteRouteImport } from './routes/plugins/route'
import { Route as PackagesRouteRouteImport } from './routes/packages/route'
import { Route as DataRouteRouteImport } from './routes/data/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as PluginsIndexRouteImport } from './routes/plugins/index'
import { Route as PackagesIndexRouteImport } from './routes/packages/index'
import { Route as DataIndexRouteImport } from './routes/data/index'
import { Route as SettingsThemeBuilderRouteImport } from './routes/settings/theme-builder'
import { Route as SettingsTemplateExtractorRouteImport } from './routes/settings/template-extractor'
import { Route as SettingsMonorepoRouteImport } from './routes/settings/monorepo'
import { Route as SettingsInfrastructureRouteImport } from './routes/settings/infrastructure'
import { Route as SettingsHierarchyRouteImport } from './routes/settings/hierarchy'
import { Route as DataModelsRouteRouteImport } from './routes/data/models/route'
import { Route as DataEnumsRouteRouteImport } from './routes/data/enums/route'
import { Route as AdminSectionsAppKeyRouteRouteImport } from './routes/admin-sections.$appKey/route'
import { Route as DataModelsIndexRouteImport } from './routes/data/models/index'
import { Route as DataEnumsIndexRouteImport } from './routes/data/enums/index'
import { Route as AdminSectionsAppKeyIndexRouteImport } from './routes/admin-sections.$appKey/index'
import { Route as PluginsEditKeyRouteImport } from './routes/plugins/edit.$key'
import { Route as PackagesLibsKeyRouteRouteImport } from './routes/packages/libs.$key/route'
import { Route as PackagesAppsKeyRouteRouteImport } from './routes/packages/apps.$key/route'
import { Route as PackagesLibsKeyIndexRouteImport } from './routes/packages/libs.$key/index'
import { Route as PackagesAppsKeyIndexRouteImport } from './routes/packages/apps.$key/index'
import { Route as PackagesAppsKeyBackendRouteImport } from './routes/packages/apps.$key/backend'
import { Route as AdminSectionsAppKeyEditSectionKeyRouteImport } from './routes/admin-sections.$appKey/edit.$sectionKey'
import { Route as PackagesAppsKeyWebRouteRouteImport } from './routes/packages/apps.$key/web/route'
import { Route as DataModelsEditKeyRouteRouteImport } from './routes/data/models/edit.$key/route'
import { Route as DataEnumsEditKeyRouteRouteImport } from './routes/data/enums/edit.$key/route'
import { Route as PackagesAppsKeyWebIndexRouteImport } from './routes/packages/apps.$key/web/index'
import { Route as DataModelsEditKeyIndexRouteImport } from './routes/data/models/edit.$key/index'
import { Route as DataEnumsEditKeyIndexRouteImport } from './routes/data/enums/edit.$key/index'
import { Route as PackagesAppsKeyWebAdminRouteImport } from './routes/packages/apps.$key/web/admin'
import { Route as DataModelsEditKeyServiceRouteImport } from './routes/data/models/edit.$key/service'
import { Route as DataModelsEditKeyGraphqlRouteImport } from './routes/data/models/edit.$key/graphql'

const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRouteRoute = PluginsRouteRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRouteRoute = PackagesRouteRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRouteRoute = DataRouteRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const PluginsIndexRoute = PluginsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PluginsRouteRoute,
} as any)
const PackagesIndexRoute = PackagesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PackagesRouteRoute,
} as any)
const DataIndexRoute = DataIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DataRouteRoute,
} as any)
const SettingsThemeBuilderRoute = SettingsThemeBuilderRouteImport.update({
  id: '/theme-builder',
  path: '/theme-builder',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsTemplateExtractorRoute =
  SettingsTemplateExtractorRouteImport.update({
    id: '/template-extractor',
    path: '/template-extractor',
    getParentRoute: () => SettingsRouteRoute,
  } as any)
const SettingsMonorepoRoute = SettingsMonorepoRouteImport.update({
  id: '/monorepo',
  path: '/monorepo',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsInfrastructureRoute = SettingsInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsHierarchyRoute = SettingsHierarchyRouteImport.update({
  id: '/hierarchy',
  path: '/hierarchy',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const DataModelsRouteRoute = DataModelsRouteRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => DataRouteRoute,
} as any)
const DataEnumsRouteRoute = DataEnumsRouteRouteImport.update({
  id: '/enums',
  path: '/enums',
  getParentRoute: () => DataRouteRoute,
} as any)
const AdminSectionsAppKeyRouteRoute =
  AdminSectionsAppKeyRouteRouteImport.update({
    id: '/admin-sections/$appKey',
    path: '/admin-sections/$appKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const DataModelsIndexRoute = DataModelsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DataModelsRouteRoute,
} as any)
const DataEnumsIndexRoute = DataEnumsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DataEnumsRouteRoute,
} as any)
const AdminSectionsAppKeyIndexRoute =
  AdminSectionsAppKeyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminSectionsAppKeyRouteRoute,
  } as any)
const PluginsEditKeyRoute = PluginsEditKeyRouteImport.update({
  id: '/edit/$key',
  path: '/edit/$key',
  getParentRoute: () => PluginsRouteRoute,
} as any)
const PackagesLibsKeyRouteRoute = PackagesLibsKeyRouteRouteImport.update({
  id: '/libs/$key',
  path: '/libs/$key',
  getParentRoute: () => PackagesRouteRoute,
} as any)
const PackagesAppsKeyRouteRoute = PackagesAppsKeyRouteRouteImport.update({
  id: '/apps/$key',
  path: '/apps/$key',
  getParentRoute: () => PackagesRouteRoute,
} as any)
const PackagesLibsKeyIndexRoute = PackagesLibsKeyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PackagesLibsKeyRouteRoute,
} as any)
const PackagesAppsKeyIndexRoute = PackagesAppsKeyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PackagesAppsKeyRouteRoute,
} as any)
const PackagesAppsKeyBackendRoute = PackagesAppsKeyBackendRouteImport.update({
  id: '/backend',
  path: '/backend',
  getParentRoute: () => PackagesAppsKeyRouteRoute,
} as any)
const AdminSectionsAppKeyEditSectionKeyRoute =
  AdminSectionsAppKeyEditSectionKeyRouteImport.update({
    id: '/edit/$sectionKey',
    path: '/edit/$sectionKey',
    getParentRoute: () => AdminSectionsAppKeyRouteRoute,
  } as any)
const PackagesAppsKeyWebRouteRoute = PackagesAppsKeyWebRouteRouteImport.update({
  id: '/web',
  path: '/web',
  getParentRoute: () => PackagesAppsKeyRouteRoute,
} as any)
const DataModelsEditKeyRouteRoute = DataModelsEditKeyRouteRouteImport.update({
  id: '/edit/$key',
  path: '/edit/$key',
  getParentRoute: () => DataModelsRouteRoute,
} as any)
const DataEnumsEditKeyRouteRoute = DataEnumsEditKeyRouteRouteImport.update({
  id: '/edit/$key',
  path: '/edit/$key',
  getParentRoute: () => DataEnumsRouteRoute,
} as any)
const PackagesAppsKeyWebIndexRoute = PackagesAppsKeyWebIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PackagesAppsKeyWebRouteRoute,
} as any)
const DataModelsEditKeyIndexRoute = DataModelsEditKeyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DataModelsEditKeyRouteRoute,
} as any)
const DataEnumsEditKeyIndexRoute = DataEnumsEditKeyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DataEnumsEditKeyRouteRoute,
} as any)
const PackagesAppsKeyWebAdminRoute = PackagesAppsKeyWebAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PackagesAppsKeyWebRouteRoute,
} as any)
const DataModelsEditKeyServiceRoute =
  DataModelsEditKeyServiceRouteImport.update({
    id: '/service',
    path: '/service',
    getParentRoute: () => DataModelsEditKeyRouteRoute,
  } as any)
const DataModelsEditKeyGraphqlRoute =
  DataModelsEditKeyGraphqlRouteImport.update({
    id: '/graphql',
    path: '/graphql',
    getParentRoute: () => DataModelsEditKeyRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/data': typeof DataRouteRouteWithChildren
  '/packages': typeof PackagesRouteRouteWithChildren
  '/plugins': typeof PluginsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/admin-sections/$appKey': typeof AdminSectionsAppKeyRouteRouteWithChildren
  '/data/enums': typeof DataEnumsRouteRouteWithChildren
  '/data/models': typeof DataModelsRouteRouteWithChildren
  '/settings/hierarchy': typeof SettingsHierarchyRoute
  '/settings/infrastructure': typeof SettingsInfrastructureRoute
  '/settings/monorepo': typeof SettingsMonorepoRoute
  '/settings/template-extractor': typeof SettingsTemplateExtractorRoute
  '/settings/theme-builder': typeof SettingsThemeBuilderRoute
  '/data/': typeof DataIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/packages/apps/$key': typeof PackagesAppsKeyRouteRouteWithChildren
  '/packages/libs/$key': typeof PackagesLibsKeyRouteRouteWithChildren
  '/plugins/edit/$key': typeof PluginsEditKeyRoute
  '/admin-sections/$appKey/': typeof AdminSectionsAppKeyIndexRoute
  '/data/enums/': typeof DataEnumsIndexRoute
  '/data/models/': typeof DataModelsIndexRoute
  '/data/enums/edit/$key': typeof DataEnumsEditKeyRouteRouteWithChildren
  '/data/models/edit/$key': typeof DataModelsEditKeyRouteRouteWithChildren
  '/packages/apps/$key/web': typeof PackagesAppsKeyWebRouteRouteWithChildren
  '/admin-sections/$appKey/edit/$sectionKey': typeof AdminSectionsAppKeyEditSectionKeyRoute
  '/packages/apps/$key/backend': typeof PackagesAppsKeyBackendRoute
  '/packages/apps/$key/': typeof PackagesAppsKeyIndexRoute
  '/packages/libs/$key/': typeof PackagesLibsKeyIndexRoute
  '/data/models/edit/$key/graphql': typeof DataModelsEditKeyGraphqlRoute
  '/data/models/edit/$key/service': typeof DataModelsEditKeyServiceRoute
  '/packages/apps/$key/web/admin': typeof PackagesAppsKeyWebAdminRoute
  '/data/enums/edit/$key/': typeof DataEnumsEditKeyIndexRoute
  '/data/models/edit/$key/': typeof DataModelsEditKeyIndexRoute
  '/packages/apps/$key/web/': typeof PackagesAppsKeyWebIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/hierarchy': typeof SettingsHierarchyRoute
  '/settings/infrastructure': typeof SettingsInfrastructureRoute
  '/settings/monorepo': typeof SettingsMonorepoRoute
  '/settings/template-extractor': typeof SettingsTemplateExtractorRoute
  '/settings/theme-builder': typeof SettingsThemeBuilderRoute
  '/data': typeof DataIndexRoute
  '/packages': typeof PackagesIndexRoute
  '/plugins': typeof PluginsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/plugins/edit/$key': typeof PluginsEditKeyRoute
  '/admin-sections/$appKey': typeof AdminSectionsAppKeyIndexRoute
  '/data/enums': typeof DataEnumsIndexRoute
  '/data/models': typeof DataModelsIndexRoute
  '/admin-sections/$appKey/edit/$sectionKey': typeof AdminSectionsAppKeyEditSectionKeyRoute
  '/packages/apps/$key/backend': typeof PackagesAppsKeyBackendRoute
  '/packages/apps/$key': typeof PackagesAppsKeyIndexRoute
  '/packages/libs/$key': typeof PackagesLibsKeyIndexRoute
  '/data/models/edit/$key/graphql': typeof DataModelsEditKeyGraphqlRoute
  '/data/models/edit/$key/service': typeof DataModelsEditKeyServiceRoute
  '/packages/apps/$key/web/admin': typeof PackagesAppsKeyWebAdminRoute
  '/data/enums/edit/$key': typeof DataEnumsEditKeyIndexRoute
  '/data/models/edit/$key': typeof DataModelsEditKeyIndexRoute
  '/packages/apps/$key/web': typeof PackagesAppsKeyWebIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/data': typeof DataRouteRouteWithChildren
  '/packages': typeof PackagesRouteRouteWithChildren
  '/plugins': typeof PluginsRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/admin-sections/$appKey': typeof AdminSectionsAppKeyRouteRouteWithChildren
  '/data/enums': typeof DataEnumsRouteRouteWithChildren
  '/data/models': typeof DataModelsRouteRouteWithChildren
  '/settings/hierarchy': typeof SettingsHierarchyRoute
  '/settings/infrastructure': typeof SettingsInfrastructureRoute
  '/settings/monorepo': typeof SettingsMonorepoRoute
  '/settings/template-extractor': typeof SettingsTemplateExtractorRoute
  '/settings/theme-builder': typeof SettingsThemeBuilderRoute
  '/data/': typeof DataIndexRoute
  '/packages/': typeof PackagesIndexRoute
  '/plugins/': typeof PluginsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/packages/apps/$key': typeof PackagesAppsKeyRouteRouteWithChildren
  '/packages/libs/$key': typeof PackagesLibsKeyRouteRouteWithChildren
  '/plugins/edit/$key': typeof PluginsEditKeyRoute
  '/admin-sections/$appKey/': typeof AdminSectionsAppKeyIndexRoute
  '/data/enums/': typeof DataEnumsIndexRoute
  '/data/models/': typeof DataModelsIndexRoute
  '/data/enums/edit/$key': typeof DataEnumsEditKeyRouteRouteWithChildren
  '/data/models/edit/$key': typeof DataModelsEditKeyRouteRouteWithChildren
  '/packages/apps/$key/web': typeof PackagesAppsKeyWebRouteRouteWithChildren
  '/admin-sections/$appKey/edit/$sectionKey': typeof AdminSectionsAppKeyEditSectionKeyRoute
  '/packages/apps/$key/backend': typeof PackagesAppsKeyBackendRoute
  '/packages/apps/$key/': typeof PackagesAppsKeyIndexRoute
  '/packages/libs/$key/': typeof PackagesLibsKeyIndexRoute
  '/data/models/edit/$key/graphql': typeof DataModelsEditKeyGraphqlRoute
  '/data/models/edit/$key/service': typeof DataModelsEditKeyServiceRoute
  '/packages/apps/$key/web/admin': typeof PackagesAppsKeyWebAdminRoute
  '/data/enums/edit/$key/': typeof DataEnumsEditKeyIndexRoute
  '/data/models/edit/$key/': typeof DataModelsEditKeyIndexRoute
  '/packages/apps/$key/web/': typeof PackagesAppsKeyWebIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/data'
    | '/packages'
    | '/plugins'
    | '/settings'
    | '/admin-sections/$appKey'
    | '/data/enums'
    | '/data/models'
    | '/settings/hierarchy'
    | '/settings/infrastructure'
    | '/settings/monorepo'
    | '/settings/template-extractor'
    | '/settings/theme-builder'
    | '/data/'
    | '/packages/'
    | '/plugins/'
    | '/settings/'
    | '/packages/apps/$key'
    | '/packages/libs/$key'
    | '/plugins/edit/$key'
    | '/admin-sections/$appKey/'
    | '/data/enums/'
    | '/data/models/'
    | '/data/enums/edit/$key'
    | '/data/models/edit/$key'
    | '/packages/apps/$key/web'
    | '/admin-sections/$appKey/edit/$sectionKey'
    | '/packages/apps/$key/backend'
    | '/packages/apps/$key/'
    | '/packages/libs/$key/'
    | '/data/models/edit/$key/graphql'
    | '/data/models/edit/$key/service'
    | '/packages/apps/$key/web/admin'
    | '/data/enums/edit/$key/'
    | '/data/models/edit/$key/'
    | '/packages/apps/$key/web/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/hierarchy'
    | '/settings/infrastructure'
    | '/settings/monorepo'
    | '/settings/template-extractor'
    | '/settings/theme-builder'
    | '/data'
    | '/packages'
    | '/plugins'
    | '/settings'
    | '/plugins/edit/$key'
    | '/admin-sections/$appKey'
    | '/data/enums'
    | '/data/models'
    | '/admin-sections/$appKey/edit/$sectionKey'
    | '/packages/apps/$key/backend'
    | '/packages/apps/$key'
    | '/packages/libs/$key'
    | '/data/models/edit/$key/graphql'
    | '/data/models/edit/$key/service'
    | '/packages/apps/$key/web/admin'
    | '/data/enums/edit/$key'
    | '/data/models/edit/$key'
    | '/packages/apps/$key/web'
  id:
    | '__root__'
    | '/'
    | '/data'
    | '/packages'
    | '/plugins'
    | '/settings'
    | '/admin-sections/$appKey'
    | '/data/enums'
    | '/data/models'
    | '/settings/hierarchy'
    | '/settings/infrastructure'
    | '/settings/monorepo'
    | '/settings/template-extractor'
    | '/settings/theme-builder'
    | '/data/'
    | '/packages/'
    | '/plugins/'
    | '/settings/'
    | '/packages/apps/$key'
    | '/packages/libs/$key'
    | '/plugins/edit/$key'
    | '/admin-sections/$appKey/'
    | '/data/enums/'
    | '/data/models/'
    | '/data/enums/edit/$key'
    | '/data/models/edit/$key'
    | '/packages/apps/$key/web'
    | '/admin-sections/$appKey/edit/$sectionKey'
    | '/packages/apps/$key/backend'
    | '/packages/apps/$key/'
    | '/packages/libs/$key/'
    | '/data/models/edit/$key/graphql'
    | '/data/models/edit/$key/service'
    | '/packages/apps/$key/web/admin'
    | '/data/enums/edit/$key/'
    | '/data/models/edit/$key/'
    | '/packages/apps/$key/web/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DataRouteRoute: typeof DataRouteRouteWithChildren
  PackagesRouteRoute: typeof PackagesRouteRouteWithChildren
  PluginsRouteRoute: typeof PluginsRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  AdminSectionsAppKeyRouteRoute: typeof AdminSectionsAppKeyRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/'
      fullPath: '/plugins/'
      preLoaderRoute: typeof PluginsIndexRouteImport
      parentRoute: typeof PluginsRouteRoute
    }
    '/packages/': {
      id: '/packages/'
      path: '/'
      fullPath: '/packages/'
      preLoaderRoute: typeof PackagesIndexRouteImport
      parentRoute: typeof PackagesRouteRoute
    }
    '/data/': {
      id: '/data/'
      path: '/'
      fullPath: '/data/'
      preLoaderRoute: typeof DataIndexRouteImport
      parentRoute: typeof DataRouteRoute
    }
    '/settings/theme-builder': {
      id: '/settings/theme-builder'
      path: '/theme-builder'
      fullPath: '/settings/theme-builder'
      preLoaderRoute: typeof SettingsThemeBuilderRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/template-extractor': {
      id: '/settings/template-extractor'
      path: '/template-extractor'
      fullPath: '/settings/template-extractor'
      preLoaderRoute: typeof SettingsTemplateExtractorRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/monorepo': {
      id: '/settings/monorepo'
      path: '/monorepo'
      fullPath: '/settings/monorepo'
      preLoaderRoute: typeof SettingsMonorepoRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/infrastructure': {
      id: '/settings/infrastructure'
      path: '/infrastructure'
      fullPath: '/settings/infrastructure'
      preLoaderRoute: typeof SettingsInfrastructureRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/hierarchy': {
      id: '/settings/hierarchy'
      path: '/hierarchy'
      fullPath: '/settings/hierarchy'
      preLoaderRoute: typeof SettingsHierarchyRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/data/models': {
      id: '/data/models'
      path: '/models'
      fullPath: '/data/models'
      preLoaderRoute: typeof DataModelsRouteRouteImport
      parentRoute: typeof DataRouteRoute
    }
    '/data/enums': {
      id: '/data/enums'
      path: '/enums'
      fullPath: '/data/enums'
      preLoaderRoute: typeof DataEnumsRouteRouteImport
      parentRoute: typeof DataRouteRoute
    }
    '/admin-sections/$appKey': {
      id: '/admin-sections/$appKey'
      path: '/admin-sections/$appKey'
      fullPath: '/admin-sections/$appKey'
      preLoaderRoute: typeof AdminSectionsAppKeyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/models/': {
      id: '/data/models/'
      path: '/'
      fullPath: '/data/models/'
      preLoaderRoute: typeof DataModelsIndexRouteImport
      parentRoute: typeof DataModelsRouteRoute
    }
    '/data/enums/': {
      id: '/data/enums/'
      path: '/'
      fullPath: '/data/enums/'
      preLoaderRoute: typeof DataEnumsIndexRouteImport
      parentRoute: typeof DataEnumsRouteRoute
    }
    '/admin-sections/$appKey/': {
      id: '/admin-sections/$appKey/'
      path: '/'
      fullPath: '/admin-sections/$appKey/'
      preLoaderRoute: typeof AdminSectionsAppKeyIndexRouteImport
      parentRoute: typeof AdminSectionsAppKeyRouteRoute
    }
    '/plugins/edit/$key': {
      id: '/plugins/edit/$key'
      path: '/edit/$key'
      fullPath: '/plugins/edit/$key'
      preLoaderRoute: typeof PluginsEditKeyRouteImport
      parentRoute: typeof PluginsRouteRoute
    }
    '/packages/libs/$key': {
      id: '/packages/libs/$key'
      path: '/libs/$key'
      fullPath: '/packages/libs/$key'
      preLoaderRoute: typeof PackagesLibsKeyRouteRouteImport
      parentRoute: typeof PackagesRouteRoute
    }
    '/packages/apps/$key': {
      id: '/packages/apps/$key'
      path: '/apps/$key'
      fullPath: '/packages/apps/$key'
      preLoaderRoute: typeof PackagesAppsKeyRouteRouteImport
      parentRoute: typeof PackagesRouteRoute
    }
    '/packages/libs/$key/': {
      id: '/packages/libs/$key/'
      path: '/'
      fullPath: '/packages/libs/$key/'
      preLoaderRoute: typeof PackagesLibsKeyIndexRouteImport
      parentRoute: typeof PackagesLibsKeyRouteRoute
    }
    '/packages/apps/$key/': {
      id: '/packages/apps/$key/'
      path: '/'
      fullPath: '/packages/apps/$key/'
      preLoaderRoute: typeof PackagesAppsKeyIndexRouteImport
      parentRoute: typeof PackagesAppsKeyRouteRoute
    }
    '/packages/apps/$key/backend': {
      id: '/packages/apps/$key/backend'
      path: '/backend'
      fullPath: '/packages/apps/$key/backend'
      preLoaderRoute: typeof PackagesAppsKeyBackendRouteImport
      parentRoute: typeof PackagesAppsKeyRouteRoute
    }
    '/admin-sections/$appKey/edit/$sectionKey': {
      id: '/admin-sections/$appKey/edit/$sectionKey'
      path: '/edit/$sectionKey'
      fullPath: '/admin-sections/$appKey/edit/$sectionKey'
      preLoaderRoute: typeof AdminSectionsAppKeyEditSectionKeyRouteImport
      parentRoute: typeof AdminSectionsAppKeyRouteRoute
    }
    '/packages/apps/$key/web': {
      id: '/packages/apps/$key/web'
      path: '/web'
      fullPath: '/packages/apps/$key/web'
      preLoaderRoute: typeof PackagesAppsKeyWebRouteRouteImport
      parentRoute: typeof PackagesAppsKeyRouteRoute
    }
    '/data/models/edit/$key': {
      id: '/data/models/edit/$key'
      path: '/edit/$key'
      fullPath: '/data/models/edit/$key'
      preLoaderRoute: typeof DataModelsEditKeyRouteRouteImport
      parentRoute: typeof DataModelsRouteRoute
    }
    '/data/enums/edit/$key': {
      id: '/data/enums/edit/$key'
      path: '/edit/$key'
      fullPath: '/data/enums/edit/$key'
      preLoaderRoute: typeof DataEnumsEditKeyRouteRouteImport
      parentRoute: typeof DataEnumsRouteRoute
    }
    '/packages/apps/$key/web/': {
      id: '/packages/apps/$key/web/'
      path: '/'
      fullPath: '/packages/apps/$key/web/'
      preLoaderRoute: typeof PackagesAppsKeyWebIndexRouteImport
      parentRoute: typeof PackagesAppsKeyWebRouteRoute
    }
    '/data/models/edit/$key/': {
      id: '/data/models/edit/$key/'
      path: '/'
      fullPath: '/data/models/edit/$key/'
      preLoaderRoute: typeof DataModelsEditKeyIndexRouteImport
      parentRoute: typeof DataModelsEditKeyRouteRoute
    }
    '/data/enums/edit/$key/': {
      id: '/data/enums/edit/$key/'
      path: '/'
      fullPath: '/data/enums/edit/$key/'
      preLoaderRoute: typeof DataEnumsEditKeyIndexRouteImport
      parentRoute: typeof DataEnumsEditKeyRouteRoute
    }
    '/packages/apps/$key/web/admin': {
      id: '/packages/apps/$key/web/admin'
      path: '/admin'
      fullPath: '/packages/apps/$key/web/admin'
      preLoaderRoute: typeof PackagesAppsKeyWebAdminRouteImport
      parentRoute: typeof PackagesAppsKeyWebRouteRoute
    }
    '/data/models/edit/$key/service': {
      id: '/data/models/edit/$key/service'
      path: '/service'
      fullPath: '/data/models/edit/$key/service'
      preLoaderRoute: typeof DataModelsEditKeyServiceRouteImport
      parentRoute: typeof DataModelsEditKeyRouteRoute
    }
    '/data/models/edit/$key/graphql': {
      id: '/data/models/edit/$key/graphql'
      path: '/graphql'
      fullPath: '/data/models/edit/$key/graphql'
      preLoaderRoute: typeof DataModelsEditKeyGraphqlRouteImport
      parentRoute: typeof DataModelsEditKeyRouteRoute
    }
  }
}

interface DataEnumsEditKeyRouteRouteChildren {
  DataEnumsEditKeyIndexRoute: typeof DataEnumsEditKeyIndexRoute
}

const DataEnumsEditKeyRouteRouteChildren: DataEnumsEditKeyRouteRouteChildren = {
  DataEnumsEditKeyIndexRoute: DataEnumsEditKeyIndexRoute,
}

const DataEnumsEditKeyRouteRouteWithChildren =
  DataEnumsEditKeyRouteRoute._addFileChildren(
    DataEnumsEditKeyRouteRouteChildren,
  )

interface DataEnumsRouteRouteChildren {
  DataEnumsIndexRoute: typeof DataEnumsIndexRoute
  DataEnumsEditKeyRouteRoute: typeof DataEnumsEditKeyRouteRouteWithChildren
}

const DataEnumsRouteRouteChildren: DataEnumsRouteRouteChildren = {
  DataEnumsIndexRoute: DataEnumsIndexRoute,
  DataEnumsEditKeyRouteRoute: DataEnumsEditKeyRouteRouteWithChildren,
}

const DataEnumsRouteRouteWithChildren = DataEnumsRouteRoute._addFileChildren(
  DataEnumsRouteRouteChildren,
)

interface DataModelsEditKeyRouteRouteChildren {
  DataModelsEditKeyGraphqlRoute: typeof DataModelsEditKeyGraphqlRoute
  DataModelsEditKeyServiceRoute: typeof DataModelsEditKeyServiceRoute
  DataModelsEditKeyIndexRoute: typeof DataModelsEditKeyIndexRoute
}

const DataModelsEditKeyRouteRouteChildren: DataModelsEditKeyRouteRouteChildren =
  {
    DataModelsEditKeyGraphqlRoute: DataModelsEditKeyGraphqlRoute,
    DataModelsEditKeyServiceRoute: DataModelsEditKeyServiceRoute,
    DataModelsEditKeyIndexRoute: DataModelsEditKeyIndexRoute,
  }

const DataModelsEditKeyRouteRouteWithChildren =
  DataModelsEditKeyRouteRoute._addFileChildren(
    DataModelsEditKeyRouteRouteChildren,
  )

interface DataModelsRouteRouteChildren {
  DataModelsIndexRoute: typeof DataModelsIndexRoute
  DataModelsEditKeyRouteRoute: typeof DataModelsEditKeyRouteRouteWithChildren
}

const DataModelsRouteRouteChildren: DataModelsRouteRouteChildren = {
  DataModelsIndexRoute: DataModelsIndexRoute,
  DataModelsEditKeyRouteRoute: DataModelsEditKeyRouteRouteWithChildren,
}

const DataModelsRouteRouteWithChildren = DataModelsRouteRoute._addFileChildren(
  DataModelsRouteRouteChildren,
)

interface DataRouteRouteChildren {
  DataEnumsRouteRoute: typeof DataEnumsRouteRouteWithChildren
  DataModelsRouteRoute: typeof DataModelsRouteRouteWithChildren
  DataIndexRoute: typeof DataIndexRoute
}

const DataRouteRouteChildren: DataRouteRouteChildren = {
  DataEnumsRouteRoute: DataEnumsRouteRouteWithChildren,
  DataModelsRouteRoute: DataModelsRouteRouteWithChildren,
  DataIndexRoute: DataIndexRoute,
}

const DataRouteRouteWithChildren = DataRouteRoute._addFileChildren(
  DataRouteRouteChildren,
)

interface PackagesAppsKeyWebRouteRouteChildren {
  PackagesAppsKeyWebAdminRoute: typeof PackagesAppsKeyWebAdminRoute
  PackagesAppsKeyWebIndexRoute: typeof PackagesAppsKeyWebIndexRoute
}

const PackagesAppsKeyWebRouteRouteChildren: PackagesAppsKeyWebRouteRouteChildren =
  {
    PackagesAppsKeyWebAdminRoute: PackagesAppsKeyWebAdminRoute,
    PackagesAppsKeyWebIndexRoute: PackagesAppsKeyWebIndexRoute,
  }

const PackagesAppsKeyWebRouteRouteWithChildren =
  PackagesAppsKeyWebRouteRoute._addFileChildren(
    PackagesAppsKeyWebRouteRouteChildren,
  )

interface PackagesAppsKeyRouteRouteChildren {
  PackagesAppsKeyWebRouteRoute: typeof PackagesAppsKeyWebRouteRouteWithChildren
  PackagesAppsKeyBackendRoute: typeof PackagesAppsKeyBackendRoute
  PackagesAppsKeyIndexRoute: typeof PackagesAppsKeyIndexRoute
}

const PackagesAppsKeyRouteRouteChildren: PackagesAppsKeyRouteRouteChildren = {
  PackagesAppsKeyWebRouteRoute: PackagesAppsKeyWebRouteRouteWithChildren,
  PackagesAppsKeyBackendRoute: PackagesAppsKeyBackendRoute,
  PackagesAppsKeyIndexRoute: PackagesAppsKeyIndexRoute,
}

const PackagesAppsKeyRouteRouteWithChildren =
  PackagesAppsKeyRouteRoute._addFileChildren(PackagesAppsKeyRouteRouteChildren)

interface PackagesLibsKeyRouteRouteChildren {
  PackagesLibsKeyIndexRoute: typeof PackagesLibsKeyIndexRoute
}

const PackagesLibsKeyRouteRouteChildren: PackagesLibsKeyRouteRouteChildren = {
  PackagesLibsKeyIndexRoute: PackagesLibsKeyIndexRoute,
}

const PackagesLibsKeyRouteRouteWithChildren =
  PackagesLibsKeyRouteRoute._addFileChildren(PackagesLibsKeyRouteRouteChildren)

interface PackagesRouteRouteChildren {
  PackagesIndexRoute: typeof PackagesIndexRoute
  PackagesAppsKeyRouteRoute: typeof PackagesAppsKeyRouteRouteWithChildren
  PackagesLibsKeyRouteRoute: typeof PackagesLibsKeyRouteRouteWithChildren
}

const PackagesRouteRouteChildren: PackagesRouteRouteChildren = {
  PackagesIndexRoute: PackagesIndexRoute,
  PackagesAppsKeyRouteRoute: PackagesAppsKeyRouteRouteWithChildren,
  PackagesLibsKeyRouteRoute: PackagesLibsKeyRouteRouteWithChildren,
}

const PackagesRouteRouteWithChildren = PackagesRouteRoute._addFileChildren(
  PackagesRouteRouteChildren,
)

interface PluginsRouteRouteChildren {
  PluginsIndexRoute: typeof PluginsIndexRoute
  PluginsEditKeyRoute: typeof PluginsEditKeyRoute
}

const PluginsRouteRouteChildren: PluginsRouteRouteChildren = {
  PluginsIndexRoute: PluginsIndexRoute,
  PluginsEditKeyRoute: PluginsEditKeyRoute,
}

const PluginsRouteRouteWithChildren = PluginsRouteRoute._addFileChildren(
  PluginsRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsHierarchyRoute: typeof SettingsHierarchyRoute
  SettingsInfrastructureRoute: typeof SettingsInfrastructureRoute
  SettingsMonorepoRoute: typeof SettingsMonorepoRoute
  SettingsTemplateExtractorRoute: typeof SettingsTemplateExtractorRoute
  SettingsThemeBuilderRoute: typeof SettingsThemeBuilderRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsHierarchyRoute: SettingsHierarchyRoute,
  SettingsInfrastructureRoute: SettingsInfrastructureRoute,
  SettingsMonorepoRoute: SettingsMonorepoRoute,
  SettingsTemplateExtractorRoute: SettingsTemplateExtractorRoute,
  SettingsThemeBuilderRoute: SettingsThemeBuilderRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface AdminSectionsAppKeyRouteRouteChildren {
  AdminSectionsAppKeyIndexRoute: typeof AdminSectionsAppKeyIndexRoute
  AdminSectionsAppKeyEditSectionKeyRoute: typeof AdminSectionsAppKeyEditSectionKeyRoute
}

const AdminSectionsAppKeyRouteRouteChildren: AdminSectionsAppKeyRouteRouteChildren =
  {
    AdminSectionsAppKeyIndexRoute: AdminSectionsAppKeyIndexRoute,
    AdminSectionsAppKeyEditSectionKeyRoute:
      AdminSectionsAppKeyEditSectionKeyRoute,
  }

const AdminSectionsAppKeyRouteRouteWithChildren =
  AdminSectionsAppKeyRouteRoute._addFileChildren(
    AdminSectionsAppKeyRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DataRouteRoute: DataRouteRouteWithChildren,
  PackagesRouteRoute: PackagesRouteRouteWithChildren,
  PluginsRouteRoute: PluginsRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  AdminSectionsAppKeyRouteRoute: AdminSectionsAppKeyRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
