name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: package.json
          registry-url: 'https://registry.npmjs.org'
          scope: '@baseplate-dev'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # v1.5.3
        with:
          publish: pnpm release
          title: 'chore: Version Packages'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Format Packages for Slack
        if: steps.changesets.outputs.published == 'true'
        id: format-packages
        run: |
          {
            echo "FORMATTED_PACKAGES<<EOF"
            echo '${{ steps.changesets.outputs.publishedPackages }}' | jq 'map(
              {
                type: "rich_text_section",
                elements: [
                  {
                    type: "text",
                    text: .name,
                    style: { bold: true }
                  },
                  {
                    type: "text",
                    text: ": "
                  },
                  {
                    type: "text",
                    text: .version
                  }
                ]
              }
            )'
            echo EOF
            } >> "$GITHUB_OUTPUT"

      - name: Send a Slack notification if a publish happens
        if: steps.changesets.outputs.published == 'true'
        uses: slackapi/slack-github-action@fcfb566f8b0aab22203f066d80ca1d7e4b5d05b3 # v1.27.1
        with:
          payload: |
            {
              "text": "New versions of Baseplate packages were just released!",
              "blocks": [
                {
                  "type": "rich_text",
                  "elements": [
                    {
                      "type": "rich_text_section",
                      "elements": [
                        {
                          "type": "text",
                          "text": "New versions of Baseplate packages were just released:"
                        }
                      ]
                    },
                    {
                      "type": "rich_text_list",
                      "elements": ${{ steps.format-packages.outputs.FORMATTED_PACKAGES}},
                      "style": "bullet"
                    }
                  ]
                }
              ]            
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
