name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: package.json
          registry-url: 'https://registry.npmjs.org'
          scope: '@baseplate-dev'

      - name: Upgrade npm to v11 # Necessary for trusted publishing
        run: npm install -g npm@11
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Create Release Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1.9.0
        with:
          publish: pnpm release
          version: pnpm run version
          title: 'chore: Version Packages'
          createGithubReleases: false

      - name: Create GitHub Release
        if: steps.changesets.outputs.published == 'true'
        run: node ./scripts/create-github-release.ts
        env:
          PUBLISHED_PACKAGES: ${{ steps.changesets.outputs.publishedPackages }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Format Packages for Slack
        if: steps.changesets.outputs.published == 'true'
        id: format-packages
        run: |
          {
            echo "FORMATTED_PACKAGES<<EOF"
            echo '${{ steps.changesets.outputs.publishedPackages }}' | jq -c 'map(
              {
                type: "rich_text_section",
                elements: [
                  {
                    type: "text",
                    text: .name,
                    style: { bold: true }
                  },
                  {
                    type: "text",
                    text: ": "
                  },
                  {
                    type: "text",
                    text: .version
                  }
                ]
              }
            )'
            echo EOF
            } >> "$GITHUB_OUTPUT"

      - name: Send a Slack notification if a publish happens
        if: steps.changesets.outputs.published == 'true'
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "New versions of Baseplate packages were just released!",
              "blocks": [
                {
                  "type": "rich_text",
                  "elements": [
                    {
                      "type": "rich_text_section",
                      "elements": [
                        {
                          "type": "text",
                          "text": "New versions of Baseplate packages were just released:"
                        }
                      ]
                    },
                    {
                      "type": "rich_text_list",
                      "elements": ${{ steps.format-packages.outputs.FORMATTED_PACKAGES}},
                      "style": "bullet"
                    }
                  ]
                }
              ]
            }
